compile: 
	gcc -m32 -o oblig3 src/oblig3.s src/test-oblig3.c
run:
	./oblig3
clean:
	-rm oblig3
	-rm test1.txt
	-rm test2.txt
	-rm test3.txt
	-rm test4.txt
	-rm test5.txt
	-rm test6.txt
	-rm test7.txt
	-rm test8.txt